[package]
name = "ex09"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex="1.5.4"
itertools = "0.10.2"
pest = "2.1.3"
pest_derive = "2.1.0"
join-lazy-fmt = "0.9.2"
